on:
  push:
    tags: 
      - 'v[0-9]+.[0-9]+.[0-9]+'

      
 
jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Install dependencies with poetry
        run: |
          poetry install
          pip install sphinx
          
      - name: Build Sphinx documentation
        run: |
          make -C docs html
      - name: Call Reusable
        uses: ./.github/workflows/publish_doc.yml
        with: 
          release: true
          secrets: inherit
       
