name: publish_doc

on:
  worflow_call: 
    inputs:
      release:
        required: true
        type: boolean
jobs: 
  deploy_docs: 
    if: {{inputs.release}}
    runs_on: ubuntu-latest
      steps: 
        - name: Deploy to GitHub Pages
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./docs/build/html


