on:
  push:
    tags: 
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-dev'
      - 'v[0-9]+.[0-9]+.[0-9]+.rc[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+.rc[0-9]+-dev'
      - 'v[0-9]+.[0-9]+.[0-9]+.alpha[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+.alpha[0-9]+-dev'
      - 'v[0-9]+.[0-9]+.[0-9]+.beta[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+.beta[0-9]+-dev'
      
 
jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Install dependencies with poetry
        run: |
          poetry install
          pip install sphinx
          
      - name: Build Sphinx documentation
        run: |
          make -C docs html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
  dummy_call: 
      needs: fix
      uses: ./.github/workflows/dummy.yml
  dummy2: 
      needs: [fix, dummy_call]
      runs-on: ubuntu-latest
      steps:  
        - name: Checkout repository2
          uses: actions/checkout@v3
  
